### PR TITLE
Add argparse, python3 support, refactor, and license

### PR DESCRIPTION
**Pull request by lionelyoung**
- Add Linux and Mac support, previous version of Windows only
- Add Python3 Support
- Refactor for readability
- Add temp and output folders

### CODE REVIEW

**Comment by eMBee** [comment]
nice, i am unclear if we can just slap any license on the code without all prior authors agreeing. to make it easier to keep that a seperate issue, could you maybe break this down into multiple commits, at least one separate one for the license?

**Comment by eMBee** [comment]
that said, you are almost rewriting the whole thing. how much of the original code is still left? :-)

**Comment by lionelyoung** [comment]
I changed this pull request to delete the LICENSE

**Comment by eMBee** [comment]
excellent

**Pull request merged**
